name: "HW-30. Test-v001"

on: push

jobs:
  api_tests_for_hw_30:
    runs-on: ubuntu-22.04
    container: 'mcr.microsoft.com/playwright:v1.59.1-jammy'
    steps:
      - name: "Checkout to tests repository"
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          ref: ${{ github.ref }}
      - name: "Install node js"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Install dependencies"
        run: npm ci
      - name: "Run tests"
        env:
          ENV: 'dev'
          HTTP_CREDENTIALS_USERNAME: ${{ secrets.HTTP_CREDENTIALS_USERNAME }}
          HTTP_CREDENTIALS_PASSWORD: ${{ secrets.HTTP_CREDENTIALS_PASSWORD }}
        run: npm run hw29
      - name: "Upload report to artifacts"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-report
          path: playwright-report/
          retention-days: 3